// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjQZl3Y9mjH1SHjgN2jeX3ub4X9wZAQ0',
    appId: '1:74308199209:web:f16612d58cc308ed61cd38',
    messagingSenderId: '74308199209',
    projectId: 'flutter-demo-1b45f',
    authDomain: 'flutter-demo-1b45f.firebaseapp.com',
    storageBucket: 'flutter-demo-1b45f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYwHgcVW39vwMt_m3WeSdFXDlBBeOCR80',
    appId: '1:74308199209:android:48ffe3be3a0d9fc761cd38',
    messagingSenderId: '74308199209',
    projectId: 'flutter-demo-1b45f',
    storageBucket: 'flutter-demo-1b45f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1mGAPAzjObCllTLILwdq-oBEru4D4rs',
    appId: '1:74308199209:ios:46da778b139d165061cd38',
    messagingSenderId: '74308199209',
    projectId: 'flutter-demo-1b45f',
    storageBucket: 'flutter-demo-1b45f.appspot.com',
    androidClientId: '74308199209-dtt9k3k0pvouhgh1ieefnmo6uhm274ug.apps.googleusercontent.com',
    iosClientId: '74308199209-qvrec21042pnscrnn54a2a850qa34tu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp1mGAPAzjObCllTLILwdq-oBEru4D4rs',
    appId: '1:74308199209:ios:46da778b139d165061cd38',
    messagingSenderId: '74308199209',
    projectId: 'flutter-demo-1b45f',
    storageBucket: 'flutter-demo-1b45f.appspot.com',
    androidClientId: '74308199209-dtt9k3k0pvouhgh1ieefnmo6uhm274ug.apps.googleusercontent.com',
    iosClientId: '74308199209-qvrec21042pnscrnn54a2a850qa34tu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQjQZl3Y9mjH1SHjgN2jeX3ub4X9wZAQ0',
    appId: '1:74308199209:web:1e6ac752b24a224961cd38',
    messagingSenderId: '74308199209',
    projectId: 'flutter-demo-1b45f',
    authDomain: 'flutter-demo-1b45f.firebaseapp.com',
    storageBucket: 'flutter-demo-1b45f.appspot.com',
  );

}